
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: l4ta
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: scdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgesql/data